### ISSUE TITLE
FYI github isn't great for a CDN

### ISSUE THREAD

**Issue by drewrwilson** [gopperman/loremDicksum#3]
https://stackoverflow.com/questions/5502540/should-github-be-used-as-a-cdn-for-javascript-libraries

Just mentioning this now because if ppl start using this as a CDN, if you end up needing to change it later, you may break their setups

**Comment by gopperman** [comment]
I read the same article and some of the other stuff linked to, and it's talking about github, not github pages. It seems like github pages is ok. I wasn't so much recommending people leech it, I just haven't put up a "download" button yet.
